version: "3.8"  # Specify the docker-compose file format version

services:
  springapp:  # Service name for your Spring Boot app
    build: .  # Build from Dockerfile in the current directory
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    environment:
      # Environment variables passed to the container
      # Spring Boot will read these via ${...} in application.properties
      SPRING_DATASOURCE_URL: jdbc:mysql://database-1.cctca4ii6jen.us-east-1.rds.amazonaws.com:3306/user_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: rootrealm
    restart: unless-stopped  # Restart policy for resilience
